package sanchez.sanchez.sergio.masoc.persistence.entity;

public enum EmailTypeEnum {
	CONFIRM_REGISTRATION_VIA_FACEBOOK, COMPLETE_ACCOUNT_DELETION, CONFIRM_ACCOUNT_ACTIVATION,
	CONFIRM_PASSWORD_CHANGE, RESET_PASSWORD, ACTIVATE_ACCOUNT, CONFIRM_REGISTRATION_VIA_GOOGLE;
}
