package sanchez.sanchez.sergio.masoc.web.rest.response;


public enum ChildrenResponseCode implements IResponseCodeTypes {

    ALL_USERS(100L), SINGLE_USER(101L),
    USER_CREATED(102L), USER_NOT_FOUND(103L), NO_CHILDREN_FOUND(104L), 
    PROFILE_IMAGE_UPLOAD_SUCCESSFULLY(105L), ALERTS_BY_SON(106L), NO_ALERTS_BY_SON_FOUNDED(107L),
    CHILD_ALERTS_CLEANED(108L), GET_ALERT_BY_ID(109L), ALERT_NOT_FOUND(110L), ALERT_BY_ID_DELETED(111L),
    CHILD_DELETED_SUCCESSFULLY(112L), SOCIAL_MEDIA_ACTIVITY_STATISTICS(113L), SOCIAL_MEDIA_ACTIVITY_STATISTICS_NOT_FOUND(114L),
    SENTIMENT_ANALYSIS_STATISTICS(115L), COMMUNITIES_STATISTICS(116L), FOUR_DIMENSIONS_STATISTICS(117L),
    NO_SENTIMENT_ANALYSIS_STATISTICS_FOR_THIS_PERIOD(118L), NO_COMMUNITY_STATISTICS_FOR_THIS_PERIOD(119L),
    NO_DIMENSIONS_STATISTICS_FOR_THIS_PERIOD(120L), SUCCESS_ALERTS_BY_SON(121L), WARNING_ALERTS_BY_SON(122L),
    INFO_ALERTS_BY_SON(123L), DANGER_ALERTS_BY_SON(124L), CHILD_WARNING_ALERTS_CLEANED(125L),
    CHILD_INFO_ALERTS_CLEANED(126L), CHILD_SUCCESS_ALERTS_CLEANED(127L), CHILD_DANGER_ALERTS_CLEANED(128L);

    private Long code;

    private ChildrenResponseCode(Long code) {
        this.code = code;
    }

    @Override
    public Long getResponseCode() {
        return code;
    }

}
